export function createInitialActors() {
    return [
        {
            id: 'actor-ministra-economia',
            name: 'Elena',
            surname: 'Santillán',
            role: 'ministro',
            province: 'capital-federal',
            partyId: 'partido-tradicional',
            age: 52,
            loyalty: 75,
            ambition: 70,
            pragmatism: 85,
            courage: 70,
            greed: 20,
            ideology: {
                economy: 30, stateSize: -20, security: 10, education: 20, environment: 0,
                trade: 40, industry: 20, liberties: 10, federalism: -10, foreignRelations: 30,
                technology: 30, health: 10, culture: 0,
            },
            influence: 90,
            wealth: 65,
            disposition: 40,
            memory: [],
            objectives: [
                { description: 'Frenar la aceleración inflacionaria y sanear las cuentas públicas', priority: 10, alignsWithPlayer: true },
            ],
        },
        {
            id: 'actor-jefe-gabinete',
            name: 'Ignacio',
            surname: 'Carrizo',
            role: 'ministro',
            province: 'sierra-industrial',
            partyId: 'partido-tradicional',
            age: 49,
            loyalty: 85,
            ambition: 60,
            pragmatism: 90,
            courage: 55,
            greed: 30,
            ideology: {
                economy: 10, stateSize: 10, security: 20, education: 30, environment: 10,
                trade: 10, industry: 30, liberties: 20, federalism: 40, foreignRelations: 10,
                technology: 20, health: 30, culture: 20,
            },
            influence: 85,
            wealth: 50,
            disposition: 60,
            memory: [],
            objectives: [
                { description: 'Garantizar la gobernabilidad y negociar acuerdos parlamentarios', priority: 10, alignsWithPlayer: true },
            ],
        },
        {
            id: 'actor-gobernadora-norte',
            name: 'Lucía',
            surname: 'Benítez',
            role: 'gobernador',
            province: 'noroeste-andino',
            partyId: 'movimiento-popular',
            age: 46,
            loyalty: 40,
            ambition: 85,
            pragmatism: 80,
            courage: 75,
            greed: 50,
            ideology: {
                economy: -30, stateSize: 50, security: 10, education: 40, environment: -20,
                trade: -30, industry: 20, liberties: 0, federalism: 90, foreignRelations: -10,
                technology: 10, health: 40, culture: 30,
            },
            influence: 80,
            wealth: 60,
            disposition: 10,
            memory: [],
            objectives: [
                { description: 'Obtener partidas adicionales de obra pública e infraestructura para el Norte', priority: 10, alignsWithPlayer: false },
            ],
        },
        {
            id: 'actor-gobernador-sur',
            name: 'Gastón',
            surname: 'Roldán',
            role: 'gobernador',
            province: 'sur-patagonico',
            partyId: 'partido-liberal',
            age: 54,
            loyalty: 35,
            ambition: 90,
            pragmatism: 75,
            courage: 80,
            greed: 60,
            ideology: {
                economy: 50, stateSize: -40, security: 30, education: 10, environment: -40,
                trade: 60, industry: 30, liberties: 20, federalism: 80, foreignRelations: 50,
                technology: 40, health: -10, culture: -10,
            },
            influence: 82,
            wealth: 85,
            disposition: -10,
            memory: [],
            objectives: [
                { description: 'Defender la autonomía de las regalías hidrocarburíferas y mineras del Sur', priority: 10, alignsWithPlayer: false },
            ],
        },
        {
            id: 'actor-presidente-banco-central',
            name: 'Marcelo',
            surname: 'Lagos',
            role: 'academico',
            province: 'capital-federal',
            partyId: null,
            age: 58,
            loyalty: 60,
            ambition: 40,
            pragmatism: 95,
            courage: 50,
            greed: 10,
            ideology: {
                economy: 40, stateSize: -30, security: 0, education: 20, environment: 0,
                trade: 50, industry: 10, liberties: 20, federalism: -30, foreignRelations: 40,
                technology: 30, health: 0, culture: 0,
            },
            influence: 88,
            wealth: 70,
            disposition: 30,
            memory: [],
            objectives: [
                { description: 'Preservar las reservas metálicas y frenar la sangría de divisas', priority: 10, alignsWithPlayer: true },
            ],
        },
        {
            id: 'actor-lider-sindical',
            name: 'Rubén',
            surname: 'Toledo',
            role: 'sindicalista',
            province: 'sierra-industrial',
            partyId: 'movimiento-popular',
            age: 61,
            loyalty: 30,
            ambition: 75,
            pragmatism: 40,
            courage: 90,
            greed: 60,
            ideology: {
                economy: -60, stateSize: 70, security: 0, education: 30, environment: -30,
                trade: -60, industry: 50, liberties: -10, federalism: 20, foreignRelations: -40,
                technology: -20, health: 60, culture: -30,
            },
            influence: 85,
            wealth: 70,
            disposition: -20,
            memory: [],
            objectives: [
                { description: 'Exigir paritarias salariales por encima de la inflación anual', priority: 10, alignsWithPlayer: false },
            ],
        },
        {
            id: 'actor-lider-opositora',
            name: 'Mariana',
            surname: 'Mansilla',
            role: 'legislador',
            province: 'capital-federal',
            partyId: 'partido-liberal',
            age: 43,
            loyalty: 10,
            ambition: 95,
            pragmatism: 85,
            courage: 80,
            greed: 40,
            ideology: {
                economy: 50, stateSize: -50, security: 40, education: 10, environment: 10,
                trade: 60, industry: -10, liberties: 30, federalism: 10, foreignRelations: 50,
                technology: 50, health: -20, culture: 10,
            },
            influence: 87,
            wealth: 75,
            disposition: -50,
            memory: [],
            objectives: [
                { description: 'Erosionar la aprobación oficial e instalar la agenda de fiscalización', priority: 10, alignsWithPlayer: false },
            ],
        },
        {
            id: 'actor-empresario-influyente',
            name: 'Arturo',
            surname: 'Paz Barreto',
            role: 'intendente',
            province: 'pampa-central',
            partyId: null,
            age: 65,
            loyalty: 40,
            ambition: 60,
            pragmatism: 90,
            courage: 40,
            greed: 80,
            ideology: {
                economy: 60, stateSize: -60, security: 20, education: 0, environment: -40,
                trade: 70, industry: 40, liberties: 20, federalism: 0, foreignRelations: 60,
                technology: 40, health: -30, culture: -20,
            },
            influence: 92,
            wealth: 98,
            disposition: 0,
            memory: [],
            objectives: [
                { description: 'Reducir retenciones e impositivos a la producción industrial y agropecuaria', priority: 10, alignsWithPlayer: false },
            ],
        },
    ];
}
export function recordActorMemory(actor, turn, event, sentiment) {
    return {
        ...actor,
        disposition: Math.max(-100, Math.min(100, actor.disposition + sentiment)),
        memory: [
            { turn, event, sentiment, decayed: false },
            ...actor.memory.slice(0, 19),
        ],
    };
}
