import type { EventTemplate } from './types';

export const EVENT_TEMPLATES: EventTemplate[] = [
  // ─── CRISIS ECONÓMICAS ───
  {
    id: 'event-sequia-pampeana',
    title: 'Sequía Severa en las Provincias Agrícolas',
    description: 'Tres meses sin lluvias significativas comprometen las cosechas de cereales y tensan las liquidaciones de exportación.',
    category: 'ambiental',
    probability: 0.12,
    cooldown: 6,
    requirements: [],
    effects: {
      national: { economy: { reserves: -6, gdp: -3 } },
      reputation: { campo: -8 },
    },
  },
  {
    id: 'event-corrida-bancaria',
    title: 'Corrida Bancaria: Cola de 6 Cuadras para Retirar Depósitos',
    description: 'Rumores de corralito provocan retiros masivos de depósitos en moneda nacional y divisas. El Banco Central emite comunicado de calma que nadie lee.',
    category: 'economico',
    probability: 0.08,
    cooldown: 10,
    requirements: [],
    effects: {
      national: { economy: { reserves: -8, inflation: 4 }, society: { trust: -8 } },
      reputation: { 'clase-media': -10, mercados: -6 },
    },
  },
  {
    id: 'event-boom-exportador',
    title: 'Boom Exportador: Suba Record del Precio de la Soja',
    description: 'La demanda china dispara los precios de los commodities agrícolas. Las divisas fluyen al Banco Central.',
    category: 'economico',
    probability: 0.1,
    cooldown: 8,
    requirements: [],
    effects: {
      national: { economy: { reserves: 8, gdp: 3 } },
      reputation: { campo: 6, mercados: 8 },
    },
  },
  {
    id: 'event-embargo-industrial',
    title: 'Bloqueo Internacional a Exportaciones del País',
    description: 'La Unión Europea impone restricciones comerciales por supuestas violaciones a tratados ambientales. Las PyMEs exportadoras están al borde.',
    category: 'internacional',
    probability: 0.06,
    cooldown: 12,
    requirements: [],
    effects: {
      national: { economy: { gdp: -4, investment: -5 }, governance: { internationalImage: -6 } },
      reputation: { inversores: -8, industria: -6 },
    },
  },
  // ─── CRISIS SOCIALES ───
  {
    id: 'event-paro-general',
    title: 'Paro General de 36 Horas',
    description: 'Las centrales sindicales unificaron un paro nacional. El país se paralizó. Manifestaciones masivas en las 8 provincias.',
    category: 'social',
    probability: 0.1,
    cooldown: 6,
    requirements: [],
    effects: {
      national: { society: { socialConflicts: 12 }, economy: { gdp: -2 } },
      reputation: { trabajadores: -8 },
      character: { popularity: -5 },
    },
  },
  {
    id: 'event-inundacion',
    title: 'Inundaciones Devastadoras en el Litoral',
    description: 'El río desbordó en cuatro provincias. 80.000 evacuados. Las imágenes de casas bajo el agua dominan los noticieros.',
    category: 'ambiental',
    probability: 0.1,
    cooldown: 8,
    requirements: [],
    effects: {
      national: { society: { poverty: 4 }, economy: { gdp: -2 } },
      character: { popularity: -3 },
    },
  },
  {
    id: 'event-escandalo-carne',
    title: 'Escándalo Sanitario: Carne Contaminada en Frigoríficos',
    description: 'La Autoridad Sanitaria Nacional detecta lotes contaminados exportados a la UE. China suspende importaciones temporalmente. El sector ganadero entra en crisis.',
    category: 'economico',
    probability: 0.07,
    cooldown: 10,
    requirements: [],
    effects: {
      national: { economy: { reserves: -5, gdp: -2 }, governance: { internationalImage: -4 } },
      reputation: { campo: -10, inversores: -6, 'organismos-internacionales': -4 },
    },
  },
  {
    id: 'event-fuga-cerebros',
    title: 'Éxodo de Profesionales: 50.000 Jóvenes Emigraron este Año',
    description: 'Ingenieros, médicos y programadores abandonan el país en busca de estabilidad. Las universidades se vacían.',
    category: 'social',
    probability: 0.09,
    cooldown: 8,
    requirements: [],
    effects: {
      national: { society: { education: -3 } },
      reputation: { jovenes: -8, universidades: -6 },
    },
  },
  // ─── EVENTOS POLÍTICOS ───
  {
    id: 'event-traicion-aliado',
    title: 'Traición en el Bloque: Aliado Clave se Pasa a la Oposición',
    description: 'El senador que te garantizaba quórum firmó un acuerdo con la oposición. Tu capacidad de legislar queda comprometida.',
    category: 'politico',
    probability: 0.1,
    cooldown: 6,
    requirements: [],
    effects: {
      national: { governance: { institutionality: -3 } },
      character: { popularity: -4 },
    },
  },
  {
    id: 'event-marcha-federal',
    title: 'Marcha Federal: 500.000 Personas en la Capital',
    description: 'Columnas de las 8 provincias convergen en la capital. Marchan por trabajo, salario y contra el ajuste. Es la manifestación más grande en una década.',
    category: 'social',
    probability: 0.08,
    cooldown: 8,
    requirements: [],
    effects: {
      national: { society: { socialConflicts: 10, polarization: 5 } },
      reputation: { trabajadores: -6, 'clase-media': -4 },
      character: { popularity: -6 },
    },
  },
  {
    id: 'event-atentado-fiscal',
    title: 'Atentado contra la sede de la Administración Tributaria',
    description: 'Un artefacto explosivo casero detonó en la fachada de la Administración Fiscal. Sin víctimas, pero el mensaje es claro.',
    category: 'politico',
    probability: 0.04,
    cooldown: 15,
    requirements: [],
    effects: {
      national: { society: { insecurity: 5, trust: -6 }, governance: { institutionality: -3 } },
      reputation: { 'fuerzas-seguridad': -4, 'clase-media': -5 },
      character: { popularity: -4 },
    },
  },
  // ─── SATÍRICOS ───
  {
    id: 'event-estatua-creciente',
    title: 'Anomalía en el Monumento Central',
    description: 'Vecinos advierten que la estatua de bronce del fundador del partido parece 5 centímetros más alta que el año pasado. La municipalidad declina hacer mediciones oficiales.',
    category: 'satirico',
    satirical: true,
    probability: 0.1,
    cooldown: 8,
    requirements: [],
    effects: {
      reputation: { jovenes: 5 },
      character: { popularity: 1 },
    },
  },
  {
    id: 'event-bancos-aeroespaciales',
    title: 'Licitación de Equipamiento Urbano "Aeroespacial"',
    description: 'Sale a la luz un pliego licitatorio para 20 bancos de plaza fabricados con polímeros termoplásticos de grado satelital. El costo unitario equivale a una ambulancia.',
    category: 'satirico',
    satirical: true,
    probability: 0.09,
    cooldown: 10,
    requirements: [],
    effects: {
      national: { governance: { corruption: 3 } },
      reputation: { prensa: -6, 'clase-media': -4 },
    },
  },
  {
    id: 'event-dinosaurio',
    title: 'Descubren Fósil de Dinosaurio en Obra Pública',
    description: 'Al cavar los cimientos de una autopista, encontraron un esqueleto de titanosaurio. La obra se pausa 6 meses. Paleontólogos festejan, constructores no.',
    category: 'satirico',
    satirical: true,
    probability: 0.08,
    cooldown: 12,
    requirements: [],
    effects: {
      national: { economy: { gdp: -1 } },
      reputation: { universidades: 8, industria: -3 },
    },
  },
  {
    id: 'event-gato-ministerio',
    title: 'El Gato del Ministerio de Interior se Hace Viral',
    description: 'Un gato callejero adoptado por los empleados del ministerio tiene más seguidores en redes que el propio ministro. Las entrevistas al gato superan en audiencia las conferencias de prensa.',
    category: 'satirico',
    satirical: true,
    probability: 0.12,
    cooldown: 8,
    requirements: [],
    effects: {
      reputation: { jovenes: 6 },
      character: { popularity: 2 },
    },
  },
  {
    id: 'event-error-tweet',
    title: 'El Community Manager Publicó desde la Cuenta Oficial',
    description: 'La cuenta oficial de la Presidencia publicó un meme insultando a la oposición. Se borró en 4 minutos. Las capturas ya tienen 2 millones de vistas.',
    category: 'satirico',
    satirical: true,
    probability: 0.1,
    cooldown: 6,
    requirements: [],
    effects: {
      reputation: { jovenes: 3, prensa: -4 },
      character: { popularity: -2, ego: 2 },
    },
  },
  // ─── EVENTOS POSITIVOS ───
  {
    id: 'event-nobel-cientifico',
    title: 'Científica del País Gana el Nobel de Medicina',
    description: 'Una investigadora del Instituto Nacional de Ciencias recibe el Premio Nobel. Ola de orgullo nacional. Todos se pelean por la foto.',
    category: 'social',
    probability: 0.05,
    cooldown: 20,
    requirements: [],
    effects: {
      national: { governance: { internationalImage: 8 }, society: { education: 3 } },
      reputation: { universidades: 12, jovenes: 8, 'organismos-internacionales': 6 },
      character: { popularity: 5 },
    },
  },
  {
    id: 'event-turismo-record',
    title: 'Temporada Turística Record en la Costa y la Patagonia',
    description: 'La devaluación atrajo una ola de turistas extranjeros. Los hoteles están colapsados. Ingresaron más dólares que nunca.',
    category: 'economico',
    probability: 0.1,
    cooldown: 8,
    requirements: [],
    effects: {
      national: { economy: { reserves: 4, tourism: 8 } },
      reputation: { 'clase-media': 4, empresarios: 6 },
    },
  },
  {
    id: 'event-vacuna-nacional',
    title: 'Laboratorio Nacional Desarrolla Vacuna Propia',
    description: 'Un laboratorio público logra una vacuna eficaz para una enfermedad regional. El mundo científico aplaude.',
    category: 'social',
    probability: 0.06,
    cooldown: 15,
    requirements: [],
    effects: {
      national: { society: { health: 5 }, governance: { internationalImage: 5 } },
      reputation: { universidades: 10, jovenes: 6, 'organismos-internacionales': 4 },
      character: { popularity: 6 },
    },
  },
];
