import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card } from '@components/ui/Card';
import { Badge } from '@components/ui/Badge';
export const DecisionFlowMap = ({ eventLog, detectedProfile }) => {
    const decisionLogs = eventLog.filter((log) => log.type === 'decision');
    return (_jsxs("div", { className: "max-w-4xl mx-auto space-y-6", children: [_jsx(Card, { title: "\uD83D\uDDFA\uFE0F Trayectoria Pol\u00EDtica y Flujo Moral", subtitle: "Mapa de decisiones que han moldeado tu gesti\u00F3n sin retorno", action: _jsxs(Badge, { variant: "gold", children: ["Perfil Actual: ", detectedProfile.toUpperCase()] }), className: "border-amber-400/30", children: _jsx("p", { className: "text-xs text-slate-300", children: "Cada opci\u00F3n tomada dej\u00F3 huella en las instituciones de la Rep\u00FAblica del Sur. No hay camino \u00FAnico correcto: solo consecuencias e inclinaciones." }) }), decisionLogs.length === 0 ? (_jsx(Card, { className: "text-center py-12", children: _jsx("p", { className: "text-slate-400 text-sm", children: "A\u00FAn no has tomado decisiones decisivas en este mandato." }) })) : (_jsx("div", { className: "relative pl-6 border-l-2 border-sky-500/40 space-y-6 my-4", children: decisionLogs.map((log, idx) => {
                    const isPragmatic = log.description.toLowerCase().includes('aporte') || log.description.toLowerCase().includes('aumento');
                    const isIdealist = log.description.toLowerCase().includes('rechazar') || log.description.toLowerCase().includes('cancelar');
                    return (_jsxs("div", { className: "relative group", children: [_jsx("div", { className: `absolute -left-[31px] top-1.5 w-4 h-4 rounded-full border-2 border-slate-950 transition-all group-hover:scale-125 ${isPragmatic ? 'bg-amber-400 shadow-lg shadow-amber-400/50' : isIdealist ? 'bg-emerald-400 shadow-lg shadow-emerald-400/50' : 'bg-sky-400 shadow-lg shadow-sky-400/50'}` }), _jsxs(Card, { className: "p-4 transition-all group-hover:border-sky-500/50", children: [_jsxs("div", { className: "flex justify-between items-center mb-1", children: [_jsxs("span", { className: "text-xs font-bold text-sky-400", children: ["Turno ", log.turn] }), _jsx(Badge, { variant: isPragmatic ? 'gold' : isIdealist ? 'emerald' : 'sky', children: isPragmatic ? '⚖️ Pragmatismo' : isIdealist ? '🕊️ Principiista' : '🏛️ Institucional' })] }), _jsx("h4", { className: "font-bold text-slate-100 text-sm", children: log.title }), _jsx("p", { className: "text-xs text-slate-300 mt-1 font-medium bg-slate-950/40 p-2 rounded border border-slate-800/80", children: log.description })] })] }, idx));
                }) }))] }));
};
