import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Modal } from '@components/ui/Modal';
import { Badge } from '@components/ui/Badge';
export const HemerotecaModal = ({ isOpen, onClose, hemeroteca, }) => {
    const [selectedIssueIdx, setSelectedIssueIdx] = useState(0);
    if (hemeroteca.length === 0)
        return null;
    const currentIssue = hemeroteca[selectedIssueIdx] ?? hemeroteca[0];
    return (_jsx(Modal, { isOpen: isOpen, onClose: onClose, title: "\uD83D\uDCDA Hemeroteca Nacional del Sur", children: _jsxs("div", { className: "space-y-6 max-h-[80vh] overflow-y-auto pr-2", children: [_jsx("p", { className: "text-xs text-slate-300", children: "Registro gr\u00E1fico e hist\u00F3rico impreso de cada mes de gobierno. Seleccion\u00E1 una edici\u00F3n para consultar la prensa de la \u00E9poca." }), _jsx("div", { className: "flex gap-1.5 overflow-x-auto pb-2 border-b border-slate-800", children: hemeroteca.map((issue, idx) => (_jsxs("button", { onClick: () => setSelectedIssueIdx(idx), className: `px-2.5 py-1.5 rounded-lg text-[11px] font-bold whitespace-nowrap transition-all cursor-pointer ${selectedIssueIdx === idx
                            ? 'bg-amber-400 text-slate-950 shadow-md'
                            : 'bg-slate-900 border border-slate-800 text-slate-300 hover:text-white hover:bg-slate-800'}`, children: ["N\u00B0 ", issue.editionNumber, " \u2014 ", issue.fortnight === 1 ? '1ª Quincena' : '2ª Quincena', " ", issue.season, " ", issue.year] }, idx))) }), _jsxs("div", { className: "p-6 rounded-2xl bg-[#f4ebd9] text-slate-900 border-4 border-[#d6c7a1] shadow-2xl font-serif", children: [_jsxs("div", { className: "border-b-2 border-slate-900 pb-3 mb-4 text-center", children: [_jsxs("div", { className: "flex justify-between text-[10px] font-bold text-slate-700 uppercase tracking-widest mb-1", children: [_jsx("span", { children: currentIssue.dateString }), _jsx("span", { children: "Rep\u00FAblica del Sur" }), _jsx("span", { children: "Precio: $120" })] }), _jsx("h1", { className: "text-4xl font-black tracking-tight text-slate-950 uppercase font-serif", children: "EL DIARIO DEL SUR" }), _jsx("p", { className: "text-[10px] text-slate-700 italic", children: "\"El decano de la prensa nacional de la Rep\u00FAblica\"" })] }), _jsxs("div", { className: "p-4 bg-[#ede0c4] rounded-lg border border-[#c4b38a] mb-4", children: [_jsx(Badge, { variant: "rose", children: currentIssue.mainHeadline.bias.toUpperCase() }), _jsx("h2", { className: "text-2xl font-black text-slate-950 mt-2 mb-1 leading-tight font-serif", children: currentIssue.mainHeadline.title }), _jsx("p", { className: "text-xs text-slate-800 font-sans italic", children: currentIssue.mainHeadline.subhead })] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-4 text-xs font-sans", children: [_jsxs("div", { className: "p-3 bg-[#ede0c4] rounded-lg border border-[#c4b38a]", children: [_jsx("h4", { className: "font-bold text-slate-950 border-b border-slate-700 pb-1 mb-2", children: "Editorial de la \u00E9poca" }), _jsx("p", { className: "text-slate-800 leading-relaxed text-[11px]", children: currentIssue.editorialText })] }), _jsxs("div", { className: "p-3 bg-[#ede0c4] rounded-lg border border-[#c4b38a]", children: [_jsx("h4", { className: "font-bold text-slate-950 border-b border-slate-700 pb-1 mb-2", children: "Humor gr\u00E1fico / Caricatura" }), _jsxs("div", { className: "p-3 bg-[#e0d0b0] rounded text-center italic text-slate-800 text-[11px]", children: ["\uD83C\uDFA8 \"", currentIssue.caricatureCaption, "\""] })] })] }), _jsxs("div", { className: "mt-4 pt-3 border-t border-slate-800 text-[10px] font-sans flex justify-between items-center text-slate-700", children: [_jsxs("span", { children: [_jsx("b", { children: "Aviso publicitario:" }), " ", currentIssue.adSatire] }), _jsxs("span", { children: [_jsx("b", { children: "Obituario:" }), " ", currentIssue.obituary] })] })] })] }) }));
};
