import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Card } from '@components/ui/Card';
import { Badge } from '@components/ui/Badge';
import { Button } from '@components/ui/Button';
import { HemerotecaModal } from './HemerotecaModal';
export const PressNewsRoom = ({ gameState }) => {
    const [activeTab, setActiveTab] = useState('diario');
    const [page, setPage] = useState(0);
    const [showHemeroteca, setShowHemeroteca] = useState(false);
    const { dailyHeadlines, mediaOutlets, eventLog, hemeroteca } = gameState;
    // Headline interactivo seleccionado para ver en noticiero o diario
    const [selectedHeadlineId, setSelectedHeadlineId] = useState(null);
    const currentIssue = hemeroteca[0] ?? {
        editionNumber: 1000 + gameState.turn,
        dateString: `${gameState.calendar.season} de ${gameState.calendar.year}`,
        editorialText: 'El país asume el costo de las medidas recientes.',
        caricatureCaption: 'El presidente haciendo malabares en el Banco Central.',
        classifieds: ['Venta de contadores de billetes.', 'Alquiler de salones de conferencia.'],
        obituary: 'Falleció la estabilidad cambiaria.',
        adSatire: 'Compre dólares cara grande en el mercado paralelo.',
    };
    const activeHeadline = (selectedHeadlineId ? dailyHeadlines.find(h => h.id === selectedHeadlineId) : null) ?? dailyHeadlines[0] ?? {
        id: 'hl-default',
        outletName: 'Canal Sur 24',
        title: 'GESTIÓN EN LA MIRA: CONFERENCIA EN LA SEDE DE GOBIERNO',
        subhead: 'Analistas debaten el impacto de las últimas medidas oficiales en el clima político nacional.',
        category: 'politico',
        bias: 'oficialista',
    };
    const recentDecisionLogs = eventLog.filter((log) => log.type === 'decision').slice(-6).reverse();
    return (_jsxs("div", { className: "max-w-5xl mx-auto space-y-6", children: [_jsx(HemerotecaModal, { isOpen: showHemeroteca, onClose: () => setShowHemeroteca(false), hemeroteca: hemeroteca }), _jsxs("div", { className: "flex justify-between items-center bg-slate-900/90 p-2 rounded-2xl border border-slate-800 shadow-xl", children: [_jsxs("div", { className: "flex flex-wrap gap-2", children: [_jsxs("button", { onClick: () => setActiveTab('diario'), className: `px-4 py-2 rounded-xl text-xs font-extrabold transition-all cursor-pointer flex items-center gap-2 ${activeTab === 'diario'
                                    ? 'bg-amber-400 text-slate-950 shadow-lg shadow-amber-400/20'
                                    : 'text-slate-400 hover:text-slate-200 hover:bg-slate-800'}`, children: [_jsx("span", { children: "\uD83D\uDDDE\uFE0F" }), " El Diario del Sur"] }), _jsxs("button", { onClick: () => setActiveTab('noticiero'), className: `px-4 py-2 rounded-xl text-xs font-extrabold transition-all cursor-pointer flex items-center gap-2 ${activeTab === 'noticiero'
                                    ? 'bg-rose-500 text-white shadow-lg shadow-rose-500/20'
                                    : 'text-slate-400 hover:text-slate-200 hover:bg-slate-800'}`, children: [_jsx("span", { children: "\uD83D\uDCFA" }), " Noticiero TV 24hs"] }), _jsxs("button", { onClick: () => setActiveTab('impacto'), className: `px-4 py-2 rounded-xl text-xs font-extrabold transition-all cursor-pointer flex items-center gap-2 ${activeTab === 'impacto'
                                    ? 'bg-sky-400 text-slate-950 shadow-lg shadow-sky-400/20'
                                    : 'text-slate-400 hover:text-slate-200 hover:bg-slate-800'}`, children: [_jsx("span", { children: "\u2696\uFE0F" }), " Impacto Moral y Repercusiones"] })] }), _jsxs(Button, { variant: "gold", size: "sm", onClick: () => setShowHemeroteca(true), children: ["\uD83D\uDCDA Hemeroteca (", hemeroteca.length, " ediciones)"] })] }), activeTab === 'diario' && (_jsx("div", { className: "space-y-6", children: _jsxs("div", { className: "bg-[#f5edd6] text-slate-950 p-8 rounded-2xl border-4 border-[#d1c49f] shadow-2xl relative font-serif", children: [_jsxs("div", { className: "border-b-2 border-slate-950 pb-4 mb-6 text-center", children: [_jsxs("div", { className: "flex justify-between text-[11px] text-slate-800 font-bold uppercase tracking-wider mb-2 font-sans", children: [_jsxs("span", { children: ["N\u00B0 ", currentIssue.editionNumber] }), _jsx("span", { children: "Rep\u00FAblica del Sur" }), _jsx("span", { children: currentIssue.dateString })] }), _jsx("h1", { className: "text-5xl font-black tracking-tight text-slate-950 font-serif my-2 uppercase", children: "EL DIARIO DEL SUR" }), _jsx("p", { className: "text-xs text-slate-800 italic font-serif", children: "\"La prensa independiente al servicio del pa\u00EDs\" \u2014 Registro hist\u00F3rico oficial" })] }), _jsx("div", { className: "flex justify-center gap-3 mb-6 font-sans", children: ['Página 1: Portada y Medios', 'Página 2: Editorial & Caricatura', 'Página 3: Clasificados & Obituarios'].map((label, idx) => (_jsx("button", { onClick: () => setPage(idx), className: `px-4 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer ${page === idx ? 'bg-slate-950 text-amber-200 shadow-md' : 'bg-[#e4d8b8] text-slate-800 hover:bg-[#d8caaa]'}`, children: label }, idx))) }), page === 0 && (_jsxs("div", { className: "space-y-4 font-sans", children: [_jsx("p", { className: "text-xs text-slate-700 italic mb-2 font-serif", children: "Hac\u00E9 clic en cualquier noticia para destacarla y ampliar informaci\u00F3n:" }), dailyHeadlines.map((hl) => {
                                    const isSelected = activeHeadline.id === hl.id;
                                    return (_jsxs("div", { onClick: () => setSelectedHeadlineId(hl.id), className: `p-5 rounded-xl transition-all cursor-pointer border ${isSelected
                                            ? 'bg-[#decfae] border-slate-950 shadow-md'
                                            : 'bg-[#eadeca] border-slate-400 hover:border-slate-700'}`, children: [_jsxs("div", { className: "flex justify-between items-center text-xs mb-2", children: [_jsx(Badge, { variant: hl.bias === 'oficialista' ? 'emerald' : hl.bias === 'opositor' ? 'rose' : 'gold', children: hl.bias.toUpperCase() }), _jsx("span", { className: "text-slate-700 text-[11px] font-semibold", children: hl.outletName })] }), _jsx("h2", { className: "text-xl font-black text-slate-950 mb-2 leading-tight font-serif", children: hl.title }), _jsx("p", { className: "text-xs text-slate-900 leading-relaxed italic font-serif", children: hl.subhead })] }, hl.id));
                                })] })), page === 1 && (_jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-4 font-sans text-xs", children: [_jsxs("div", { className: "p-4 bg-[#eadeca] rounded-xl border border-slate-400", children: [_jsx("h4", { className: "font-bold text-slate-950 border-b border-slate-600 pb-1 mb-2 font-serif text-sm", children: "Editorial pol\u00EDtica del per\u00EDodo" }), _jsx("p", { className: "text-slate-900 leading-relaxed text-[12px] font-serif", children: currentIssue.editorialText })] }), _jsxs("div", { className: "p-4 bg-[#eadeca] rounded-xl border border-slate-400", children: [_jsx("h4", { className: "font-bold text-slate-950 border-b border-slate-600 pb-1 mb-2 font-serif text-sm", children: "Caricatura pol\u00EDtica" }), _jsxs("div", { className: "p-4 bg-[#decfae] rounded text-center italic text-slate-900 text-xs font-serif", children: ["\uD83C\uDFA8 \"", currentIssue.caricatureCaption, "\""] })] })] })), page === 2 && (_jsxs("div", { className: "space-y-4 font-sans", children: [_jsxs("div", { className: "p-4 bg-[#eadeca] rounded-xl border border-slate-400 text-xs", children: [_jsx("h4", { className: "font-bold text-slate-950 mb-2 font-serif text-sm", children: "L\u00EDnea editorial de medios nacionales" }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-3", children: mediaOutlets.slice(0, 4).map((m) => (_jsx("div", { className: "p-2.5 bg-[#dfcfad] rounded border border-slate-400/80", children: _jsxs("div", { className: "flex justify-between font-bold text-slate-950 text-xs", children: [_jsx("span", { children: m.name }), _jsxs("span", { className: "text-emerald-700", children: [m.credibility, "% credibilidad"] })] }) }, m.id))) })] }), _jsxs("div", { className: "p-3 bg-[#eadeca] rounded-xl border border-slate-400 text-[11px] flex flex-wrap gap-4 justify-between", children: [_jsxs("span", { children: [_jsx("b", { children: "Aviso sat\u00EDrico:" }), " ", currentIssue.adSatire] }), _jsxs("span", { children: [_jsx("b", { children: "Obituario:" }), " ", currentIssue.obituary] })] })] }))] }) })), activeTab === 'noticiero' && (_jsxs("div", { className: "space-y-6 font-sans", children: [_jsx("style", { children: `
              @keyframes bgGradient {
                0% { background-position: 0% 50%; }
                50% { background-position: 100% 50%; }
                100% { background-position: 0% 50%; }
              }
              @keyframes rotateGlobe {
                0% { transform: rotate(0deg); }
                100% { transform: rotate(360deg); }
              }
              @keyframes scrollTicker {
                0% { transform: translateX(100vw); }
                100% { transform: translateX(-100%); }
              }
            ` }), _jsxs("div", { className: "relative rounded-2xl overflow-hidden border border-slate-700 aspect-video max-h-[440px] flex flex-col justify-between shadow-2xl", style: {
                            background: 'linear-gradient(270deg, #020617, #0f172a, #020617)',
                            backgroundSize: '200% 200%',
                            animation: 'bgGradient 15s ease infinite',
                        }, children: [_jsx("div", { className: "absolute inset-0 overflow-hidden pointer-events-none opacity-20 flex items-center justify-center", children: _jsxs("div", { className: "rounded-full border border-slate-500/30", style: { width: '800px', height: '800px', animation: 'rotateGlobe 60s linear infinite' }, children: [_jsx("div", { className: "absolute top-1/2 left-0 w-full h-px bg-slate-500/20" }), _jsx("div", { className: "absolute top-0 left-1/2 w-px h-full bg-slate-500/20" })] }) }), _jsxs("div", { className: "flex justify-between items-center z-10 p-6", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("span", { className: "bg-red-600 text-white font-bold text-[10px] px-3 py-1 rounded-sm uppercase tracking-widest shadow-md", children: "EN VIVO" }), _jsx("span", { className: "text-white font-bold text-sm tracking-[0.2em] opacity-90", children: activeHeadline.outletName.toUpperCase() })] }), _jsx(Badge, { variant: "rose", children: activeHeadline.bias.toUpperCase() })] }), _jsxs("div", { className: "z-10 mt-auto flex flex-col w-full", children: [_jsxs("div", { className: "bg-slate-900/95 border-t border-slate-700/50 backdrop-blur-md px-8 py-6 relative", children: [_jsx("div", { className: "absolute top-0 left-0 w-1.5 h-full bg-amber-500" }), _jsx("span", { className: "text-[10px] font-bold text-amber-500 uppercase tracking-widest block mb-1", children: "\u00DALTIMO MOMENTO \u2014 COBERTURA EN DIRECTO" }), _jsx("h2", { className: "text-xl md:text-3xl font-black text-white tracking-tight leading-tight mb-2", children: activeHeadline.title }), _jsx("div", { className: "text-xs md:text-sm text-slate-300 font-medium max-w-3xl leading-relaxed", children: activeHeadline.subhead })] }), _jsxs("div", { className: "bg-amber-500 px-4 py-2 flex items-center overflow-hidden whitespace-nowrap", children: [_jsx("span", { className: "bg-slate-950 text-white text-[10px] font-black px-3 py-1 mr-4 z-20 shadow-md uppercase", children: "TITULARES" }), _jsx("div", { className: "flex-1 overflow-hidden relative h-5", children: _jsx("div", { className: "absolute whitespace-nowrap flex gap-12 items-center h-full text-slate-950 font-bold text-xs", style: { animation: 'scrollTicker 35s linear infinite' }, children: dailyHeadlines.map((hl) => (_jsxs("span", { className: "cursor-pointer hover:underline", children: ["\u25A0 [", hl.outletName, "] ", hl.title] }, hl.id))) }) })] })] })] }), _jsxs("div", { className: "space-y-2", children: [_jsx("h4", { className: "text-xs font-bold text-slate-300 uppercase tracking-wider", children: "Seleccionar noticia para transmitir en vivo:" }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-3", children: dailyHeadlines.map((hl) => (_jsxs("button", { onClick: () => setSelectedHeadlineId(hl.id), className: `p-3.5 rounded-xl border text-left transition-all cursor-pointer text-xs ${activeHeadline.id === hl.id
                                        ? 'bg-sky-950/80 border-sky-400 text-sky-100 shadow-md'
                                        : 'bg-slate-900/60 border-slate-800 text-slate-300 hover:border-slate-700'}`, children: [_jsxs("div", { className: "flex justify-between items-center text-[10px] text-slate-400 font-bold mb-1", children: [_jsx("span", { children: hl.outletName }), _jsx("span", { className: "capitalize", children: hl.category })] }), _jsx("div", { className: "font-bold text-slate-100 line-clamp-1", children: hl.title })] }, hl.id))) })] })] })), activeTab === 'impacto' && (_jsx("div", { className: "space-y-6", children: _jsx(Card, { title: "\u2696\uFE0F Balance de responsabilidad y sentimiento humano", subtitle: "C\u00F3mo tus elecciones recientes cambiaron la vida cotidiana de las personas", children: recentDecisionLogs.length === 0 ? (_jsx("p", { className: "text-slate-400 text-xs text-center py-6", children: "A\u00FAn no has tomado decisiones decisivas en este mandato." })) : (_jsx("div", { className: "space-y-4", children: recentDecisionLogs.map((log, idx) => (_jsxs("div", { className: "p-4 rounded-xl bg-slate-900/80 border border-slate-800 space-y-2", children: [_jsxs("div", { className: "flex justify-between items-center", children: [_jsxs("span", { className: "text-xs font-bold text-sky-400", children: ["Turno ", log.turn] }), _jsx(Badge, { variant: "gold", children: "Decisi\u00F3n ejecutada" })] }), _jsx("h4", { className: "font-bold text-slate-100 text-sm", children: log.title }), _jsxs("p", { className: "text-xs text-amber-200 italic bg-amber-950/40 p-3 rounded-lg border border-amber-500/30 font-medium", children: ["\uD83D\uDCAC \"", log.emotionalText ?? log.description, "\""] })] }, idx))) })) }) }))] }));
};
